version: 2

jobs:
  build-deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build docs
          command: yarn build
      - run:
          name: Configure build
          command: |
            git config user.email "naiyer.app+circleci@gmail.com"
            git config user.name "circleci-build"
      - add_ssh_keys:
          fingerprints:
            - "b4:2e:4a:5b:ec:99:71:ae:6b:db:6c:f0:bc:ea:22:21"
      - run:
          name: Deploy the build
          command: yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: release      
