name: deploy

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Generate LFS lockfile
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > lfs.lock
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('lfs.lock') }}-v1
      - name: Pull new LFS files
        run: git lfs pull
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Restore Node cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-v1
      - name: Install dependencies
        run: npm install
      - name: Print environment
        run: npm run get:info
      - name: Generate the build
        run: npm run build
      - name: Publish on Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=public
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
